### Chapter 1: Get all payments
GET http://localhost:3000/payments

### Chapter 2: Get one payment by route parameter
GET http://localhost:3000/payments/1

### Chapter 3: Filter payments by paid status
GET http://localhost:3000/payments?status=paid

### Chapter 3: Filter payments by pending status
GET http://localhost:3000/payments?status=pending

### Chapter 4: Create a new payment
POST http://localhost:3000/payments
Content-Type: application/json

{
  "invoiceNo": "BTN-003",
  "customer": "Dorji Mart",
  "amount": 3000,
  "status": "pending"
}
